lang_lookup = {
    en: {
        ISO_CODE: 'en',
        BEGIN_NEW: "begin new",
        VIEW_PREVIOUS: "view previous sessions",
        UPDATE: "update",
        BACK: "back",
        RESTART: "restart",
        DELETE: "delete",
        SAVE: "save",
				ASSESSMENT_SAVED: 'Assessment Saved',
        NOTES: "notes",
        SYMPTOMS: "symptoms",
        PROBE: "probe",
        ANSWERS: "answers",
        RESULTS: "results",
        PRINT: "print",
        AUTHENTICATION: "login",
        USER_NAME: "user name",
        PASSWORD: "password",
        LOGIN: "login",
		REGISTRATION: 'registration',
        REGISTER: "register",
        CONFIRM: "confirm",
        LOGIN_FAIL: "That username/password is incorrect",
        NOT_VALID: "SUB1 is not a valid SUB2.",
        INCOMPLETE: "Complete all inputs on this page.",
        CRITERIA_MET: 'Criteria for SUB met.',
        NEED_LOGIN: 'You need to login in order to perform that action. Would you like to log in now?',
        USER_NO_BLANK: 'The username can not be blank',
        PASS_NO_BLANK: 'The password can not be blank',
        CONFIRM_NO_BLANK: 'The confirm box can not be blank',
        USER_NOT_AVAILABLE: 'That username is not available',

        SUCCESS_UPDATE:'You have successfully updated the questionnaire.',
        UPDATE_ANYWAY: "You're version is up to date. Would you still like to re-install it?",
        UPDATE_UNAVAILABLE: 'Update Unavailable',
        SUCCESS_UPDATE:'You have successfully updated the questionnaire.',
        UPDATE_ANYWAY: "You're version is up to date. Would you still like to re-install it?",
        UPDATE_UNAVAILABLE: 'Update Unavailable',
        CONNECT_INTERNET: 'Please connect to the internet before updating the questionnaire.',

        CONNECT_INTERNET: 'Please connect to the internet before updating the questionnaire.',
        PASSWORDS_NO_MATCH: "the passwords you entered do not match",
        REGISTER_SUCCESS: "You are registered. Press the back button to return to the interview",
        INTERVIEW: 'Interview',
        DATE: 'Date',
        INTERVIEW_ID: 'Interview ID',
        SUBJECT_ID: 'Subject ID',
        SUBJECT_AGE: 'Subect Age',
        BMI: 'BMI',
        WEIGHT: 'Weight',
        HEIGHT: 'Height',
        RECENT_WEIGHT: 'Recent Weight',
        RECENT_HEIGHT: 'Recent Height',
        RECENT_LOW_BMI: 'Recent Low BMI',
        DIAGNOSIS: 'Diagnosis',
        ANOREXIA_NERVOSA: 'Anorexia Nevosa',
        BINGE_PURGE_SUBTYPE: 'Binge-Purge Subtype',
        RESTRICTING_SUBTYPE: 'Restricting Subtype',
        BULIMIA_NERVOSA: 'Bulimia Nervosa',
        BINGE_EATING_DISORDER: 'Binge Eating Disorder',
        PICA: 'Pica',
        RUMINATION_DISORDER: 'Rumination Disorder',
        AVOIDANT_RESTRICTIVE: 'Avoidant/Restrictive Food Intake Disorder',
        TYPICAL_OBE_ITEMS: 'Typical OBE items',
        OBES_PER_WEEK: 'OBEs per week',
        TYPICAL_SBE_ITEMS: 'Typical SBE items',
        SBES_PER_WEEK: 'SBEs per week',
        SBES_PER_MONTH: 'SBEs per month',
        VOMITING: 'Vomiting',
        LAXATIVES: 'Laxitives',
        DIURETICS: 'Diuretics',
        AVERAGE_NO_WEEK: 'Average # per week',
        AVERAGE_NO_MONTH: 'Average # per month',
        OTHER_METHOD: 'Other method',
        NAME: 'Name',
        EXERCISE: 'Exercise',
        TYPE: 'Exercise Type',
        AVERAGE_MINUTES_PER: 'Average number mins per episode',
        AVERAGE_PER_WEEK: 'Average number episodes per week',
        AVERAGE_PER_MONTH: 'Average number episodes per month',
        NOTES: 'Notes'
    },
    no: {
        ISO_CODE: 'no',
        BEGIN_NEW: "Start nytt intervju",
        VIEW_PREVIOUS: "Se tidligere intervjuer",
        UPDATE: "Oppdater",
        BACK: "Tilbake",
        RESTART: "Omstart",
        DELETE: "Slett",
        SAVE: "Lagre",
				ASSESSMENT_SAVED: 'Intervjuet er lagret',
        NOTES: "Notater",
        SYMPTOMS: "Symptomer",
        PROBE: "Spørsmål",
        ANSWERS: "Svar",
        RESULTS: "resultater",
        PRINT: "Skriv ut",
        AUTHENTICATION: "Innlogging",
        USER_NAME: "Brukernavn",
        PASSWORD: "Passord",
        LOGIN: "Logg på",
		REGISTRATION: "Registrering",
        REGISTER: "Registrer",
        CONFIRM: "Bekreft passord",
        LOGIN_FAIL: "Brukernavnet/passordet eksisterer ikke",
        NOT_VALID: "SUB1 er ikke en gyldig SUB2",
        INCOMPLETE: "Fyll ut all informasjon på denne siden.",
        CRITERIA_MET: 'Oppfyller kriteriene for SUB.',
        NEED_LOGIN: "Du må logge in eller registrere deg for å lagre/se tidligere intervjuer. Ønsker du å logge in eller registrere deg nå?",
        USER_NO_BLANK: "Alle felt må fylles ut",
        PASS_NO_BLANK: 'The password can not be blank',
        CONFIRM_NO_BLANK: 'The confirm box can not be blank',
        USER_NOT_AVAILABLE: 'Brukernavnet er ikke tilgjenglig',

        SUCCESS_UPDATE:'You have successfully updated the questionnaire.',
        UPDATE_ANYWAY: "You're version is up to date. Would you still like to re-install it?",
        UPDATE_UNAVAILABLE: 'Update Unavailable',
        SUCCESS_UPDATE:'You have successfully updated the questionnaire.',
        UPDATE_ANYWAY: "You're version is up to date. Would you still like to re-install it?",
        UPDATE_UNAVAILABLE: 'Update Unavailable',
        CONNECT_INTERNET: 'Please connect to the internet before updating the questionnaire.',

        CONNECT_INTERNET: 'Please connect to the internet before updating the questionnaire.',
        PASSWORDS_NO_MATCH: "Du har oppgitt forskjellige passord",
        REGISTER_SUCCESS: "Du er registrert. Klikk Tilbake for å gå tilbake til intervjuet",
        INCOMPLETE: "Fyll ut all informasjon på denne siden.",
        CRITERIA_MET: 'Oppfyller kriteriene for SUB.',
        INTERVIEW: 'Intervju',
        DATE: 'dato',
        INTERVIEW_ID: 'ID intervjuere',
        SUBJECT_ID: 'ID individ',
        SUBJECT_AGE: 'Individets alder',
        BMI: 'KMI',
        WEIGHT: 'Vekt',
        HEIGHT: 'Høyde',
        RECENT_WEIGHT: 'Nylig vekt',
        RECENT_HEIGHT: 'Nylig høyde',
        RECENT_LOW_BMI: 'Nylig lav KMI',
        DIAGNOSIS: 'Diagnose',
        ANOREXIA_NERVOSA: 'Anoreksia Nervosa',
        BINGE_PURGE_SUBTYPE: 'Bulemisk Subtype',
        RESTRICTING_SUBTYPE: 'Restriktiv Subtype',
        BULIMIA_NERVOSA: 'Bulimi Nervosa',
        BINGE_EATING_DISORDER: 'Overspisingslidelse',
        PICA: 'Pica',
        RUMINATION_DISORDER: 'Regurgitasjonsforstyrrelse',
        AVOIDANT_RESTRICTIVE: 'Unnvikende/restriktiv matinntaksforstyrrelse',
        TYPICAL_OBE_ITEMS: 'Eksempel på typisk UOO',
        OBES_PER_WEEK: 'Antall UOO per uke',
        TYPICAL_SBE_ITEMS: 'Eksempel på typisk USO',
        SBES_PER_WEEK: 'Antall USO per uke',
        SBES_PER_MONTH: 'Antall USO per måned',

        VOMITING: 'Oppkast',
        LAXATIVES: 'Avføringsmiddel',
        DIURETICS: 'Vanndrivende midler',
        AVERAGE_NO_WEEK: 'Gjennomsnittlig hyppighet per uke',
        AVERAGE_NO_MONTH: 'Gjennomsnittlig antall per måned',
        OTHER_METHOD: 'Andre metoder',
        NAME: 'Beskrivelse',
        EXERCISE: 'Trening',
        TYPE: 'Type trening',
        AVERAGE_MINUTES_PER: 'Antall minutter per treningsøkt i gjennomsnitt',
        AVERAGE_PER_WEEK: 'Antall episoder, i gjennomsnitt, av overdreven trening per uke',
        AVERAGE_PER_MONTH: 'Antall episoder, i gjennomsnitt, av overdreven trening per måned',
        NOTES: 'Notater'
    },
	sp:	{
	ISO_CODE: "sp",
        BEGIN_NEW: "Comenzar nueva sesión",
        VIEW_PREVIOUS: "Ver sesiones anteriores",
        UPDATE: "Actualizar",
        BACK: "Atrás",
        RESTART: "Reiniciar",
        DELETE: "Borrar",
        SAVE: "Salvar",
		ASSESSMENT_SAVED: 'Evaluación guardada',
        NOTES: "Notas",
        SYMPTOMS: "Síntomas",
        PROBE: "Exploración",
        ANSWERS: "Respuestas",
        RESULTS: "Resultados",
        PRINT: "Impresión",
        AUTHENTICATION: "Autenticación",
        USER_NAME: "Nombre de usuario",
        PASSWORD: "Contraseña",
        LOGIN: "Iniciar sesión",
		REGISTRATION: "Matriculación",
        REGISTER: "Registrer",
        CONFIRM: "Confirmar",
        LOGIN_FAIL: "Carga fallida",
        NOT_VALID: "No es válido",
        INCOMPLETE: "Incompleto",
        NEED_LOGIN: "Necesidad de acceso",
        USER_NO_BLANK: "Usuario no en  blanco",
        PASS_NO_BLANK: 'No dejar en blanco',
        CONFIRM_NO_BLANK: 'Confirmar sin espacio en blanco',
        USER_NOT_AVAILABLE: 'Usuario no disponible',

        SUCCESS_UPDATE:'You have successfully updated the questionnaire.',
        UPDATE_ANYWAY: "You're version is up to date. Would you still like to re-install it?",
        UPDATE_UNAVAILABLE: 'Update Unavailable',
        SUCCESS_UPDATE:'You have successfully updated the questionnaire.',
        UPDATE_ANYWAY: "You're version is up to date. Would you still like to re-install it?",
        UPDATE_UNAVAILABLE: 'Update Unavailable',
        CONNECT_INTERNET: 'Please connect to the internet before updating the questionnaire.',

        CONNECT_INTERNET: 'Please connect to the internet before updating the questionnaire.',
        PASSWORDS_NO_MATCH: "Contraseñas no coinciden",
        REGISTER_SUCCESS: "Registrar el éxito",
        INCOMPLETE: "Incompleto",
        CRITERIA_MET: 'Criterios cumplidos para SUB',
        INTERVIEW: 'Entrevista',
        DATE: 'Fecha',
        INTERVIEW_ID: 'ID de la entrevista',
        SUBJECT_ID: 'ID de sujeto',
        SUBJECT_AGE: 'Edad del sujeto',
        BMI: 'IMC',
        WEIGHT: 'Peso',
        HEIGHT: 'Altura',
        RECENT_WEIGHT: 'Peso reciente',
        RECENT_HEIGHT: 'Altura reciente',
        RECENT_LOW_BMI: 'IMC bajo reciente',
        DIAGNOSIS: 'Diagnóstico',
        ANOREXIA_NERVOSA: 'Anorexia nerviosa',
        BINGE_PURGE_SUBTYPE: 'Los atracones y purgas subtipo',
        RESTRICTING_SUBTYPE: 'Subtipo restrictivo',
        BULIMIA_NERVOSA: 'Bulimia Nerviosa',
        BINGE_EATING_DISORDER: 'Trastorno por atracón',
        PICA: 'PICA',
        RUMINATION_DISORDER: 'Trastorno de rumiación',
        AVOIDANT_RESTRICTIVE: 'Evitando restrictivo',
        TYPICAL_OBE_ITEMS: 'Artículos típicos de EAO',
        OBES_PER_WEEK: 'EAOS por semana',
        TYPICAL_SBE_ITEMS: 'Artículos típicos de EAS',
        SBES_PER_WEEK: 'EASS por semana',
        SBES_PER_MONTH: 'SBES por mes',

        VOMITING: 'Vómitos',
        LAXATIVES: 'Laxantes',
        DIURETICS: 'Diuréticos',
        AVERAGE_NO_WEEK: 'Promedio de semanas',
        AVERAGE_NO_MONTH: 'Número medio de meses',
        OTHER_METHOD: 'Otro método',
        NAME: 'Nombre',
        EXERCISE: 'Ejercicio',
        TYPE: 'Tipo',
        AVERAGE_MINUTES_PER: 'Minutos promedio por',
        AVERAGE_PER_WEEK: 'Promedia por semana',
        AVERAGE_PER_MONTH: 'Promedia por mes',
        NOTES: 'Notas'
	},
	
    tr:{
        ISO_CODE: 'tr',
        BEGIN_NEW: 'şimdi başlayın',
        VIEW_PREVIOUS: 'önceki oturumları görüntüleyin',
        UPDATE: 'güncelle',
        BACK: 'geri',
        RESTART: 'tekrar başlat',
        DELETE: 'sil',
        SAVE: 'kaydet',
				ASSESSMENT_SAVED: 'Değerlendirme kaydedildi',
        NOTES: 'notlar',
        SYMPTOMS: 'belirtiler',
        PROBE: 'ayrıntılı sorgulama',
        ANSWERS: 'yanıtlar',
        RESULTS: 'sonuçlar',
        PRINT: 'yazdır',
        AUTHENTICATION: 'oturum aç',
        USER_NAME: 'kullanıcı adı',
        PASSWORD: 'şifre',
        LOGIN: 'oturum aç',
		REGISTRATION: 'kayıt',
        REGISTER: 'kayıt ol',
        CONFIRM: 'onayla',
        LOGIN_FAIL: 'Bu kullanıcı adı/şifre yanlış',
        NOT_VALID: 'Eşikaltı1 (SUB1),eşikaltı2 (SUB2) için geçerli değildir.',
        INCOMPLETE: 'Bu sayfadaki tüm girdileri tamamla.',
        CRITERIA_MET: 'Eşikaltı (SUB) için kriter karşılandı.',
        NEED_LOGIN: 'Bu eylemi gerçekleştirmek için oturum açmanız gerekmektedir. Şimdi giriş yapmak ister misiniz?',
        USER_NO_BLANK: 'Kullanıcı adı boş bırakılamaz',
        PASS_NO_BLANK: 'Şifre boş bırakılamaz',
        CONFIRM_NO_BLANK: 'Onay kutusu boş bırakılamaz', 
        USER_NOT_AVAILABLE: 'Bu kullanıcı adı mevcut değil',

        SUCCESS_UPDATE:'Anketi başarıyla güncellediniz.',
        UPDATE_ANYWAY: 'Sürümünüz güncel. Yine de yeniden yüklemek ister misiniz?',
        UPDATE_UNAVAILABLE: 'Güncelleme bulunamadı',
        SUCCESS_UPDATE:'Anketi başarıyla güncellediniz.',
        UPDATE_ANYWAY: 'Sürümünüz güncel. Yine de yeniden yüklemek ister misiniz?',
        UPDATE_UNAVAILABLE: 'Güncelleme bulunamadı',
        CONNECT_INTERNET: 'Lütfen anketi güncellemeden önce internete bağlanın.',

        CONNECT_INTERNET: 'Lütfen anketi güncellemeden önce internete bağlanın.',
        PASSWORDS_NO_MATCH: 'Girdiğiniz şifreler birbiri ile uyuşmuyor',
        REGISTER_SUCCESS: 'Kayıt oldunuz. Görüşmeye dönmek için geri tuşuna basınız',
        INTERVIEW: 'Görüşme',
        DATE: 'Tarih',
        INTERVIEW_ID: 'Görüşme Kimliği',
        SUBJECT_ID: 'Katılımcı Kimliği',
        SUBJECT_AGE: 'Katılımcı Yaşı',
        BMI: 'BKİ',
        WEIGHT: 'Kilo',
        HEIGHT: 'Boy',
        RECENT_WEIGHT: 'Yakın Tarihli Kilo',
        RECENT_HEIGHT: 'Yakın Tarihli Boy',
        RECENT_LOW_BMI: 'Yakın Tarihli Düşük BKİ',
        DIAGNOSIS: 'Tanı',
        ANOREXIA_NERVOSA: 'Anoreksiya Nervoza',
        BINGE_PURGE_SUBTYPE: 'Tıkınırcasına yeme-Çıkartma Alt tipi',
        RESTRICTING_SUBTYPE: 'Kısıtlayıcı Alt Tipi',
        BULIMIA_NERVOSA: 'Bulimiya Nervoza',
        BINGE_EATING_DISORDER: 'Tıkınırcasına Yeme Bozukluğu',
        PICA: 'Pika',
        RUMINATION_DISORDER: 'Geri Çıkarma (Geviş Getirme) Bozukluğu',
        AVOIDANT_RESTRICTIVE: 'Kaçıngan/Kısıtlı Yiyecek Alım Bozukluğu',
        TYPICAL_OBE_ITEMS: 'Tipik NTY atağı maddeleri',
        OBES_PER_WEEK: 'Haftalık NTY atakları',
        TYPICAL_SBE_ITEMS: 'Tipik ÖTY atağı maddeleri',
        SBES_PER_WEEK: 'Haftalık ÖTY atakları',
        SBES_PER_MONTH: 'Aylık ÖTY atakları',
        VOMITING: 'Kusma',
        LAXATIVES: 'Laksatifler',
        DIURETICS: 'İdrar söktürücüler',
        AVERAGE_NO_WEEK: 'Haftalık ortalama',
        AVERAGE_NO_MONTH: 'Aylık ortalama',
        OTHER_METHOD: 'Diğer yöntemler',
        NAME: 'AD',
        EXERCISE: 'Egzersiz',
        TYPE: 'Egzersiz Türü',
        AVERAGE_MINUTES_PER: 'Her bir atağın ortalama dakikası',
        AVERAGE_PER_WEEK: 'Haftalık ortalama atakların sayısı',
        AVERAGE_PER_MONTH: 'Aylık ortalama atakların sayısı',
        NOTES: 'Notlar'
    }
}

//lang_lookup['tr'] = JSON.parse(JSON.stringify(lang_lookup['en']));
//lang_lookup['tr']['ISO_CODE'] = 'tr';

function get_language(){
    var prefered = null;

    var languages = navigator.languages
    if (languages && languages.length > 1){
        prefered =languages[0];

    }
//    var params = Ext.urlDecode(location.search.substring(1));
    if (PARAMS.lang){
        prefered = PARAMS.lang;

    }
    if (prefered){
        switch(true){
            case /en/.test(prefered):
                return lang_lookup['en'];
                break;
            case /no/.test(prefered):
                return lang_lookup['no'];
                break;
            case /sp/.test(prefered):
                return lang_lookup['sp'];
                break;
            case /tr/.test(prefered):
                return lang_lookup['tr'];
                break;
            default:
                return lang_lookup['en'];
        }
    }
    return lang_lookup['en'];
}

var lang = get_language();

